#!/bin/bash
WORKTREE_DIR="$PWD"
TEST_DIR=".tests-${GIT_AUTHOR_DATE% +*}"
git archive "$(git write-tree)" --prefix="$TEST_DIR/" | tar xf -
cd "$TEST_DIR"
if bash ./pipadoc.test 2>&1 | tee test.log ; then
    ret=$?
    lua pipadoc.lua -m asciidoc pipadoc.lua >pipadoc.txt &&
        asciidoc -a toc pipadoc.txt &&
        grep -v '^// ' pipadoc.txt >README &&
        if git diff --numstat README |
                { read a r f ; test $((a+r)) -gt 2; }; then
            mv README pipadoc.html "$WORKTREE_DIR/"
            cd "$WORKTREE_DIR"
            git add README pipadoc.html
        fi
else
    ret=$?
    echo "testsuite failed, abort commit" 1>&2
fi

exit $ret
