#!/bin/bash
KEEP_TESTS=5
WORKTREE_DIR="$PWD"
TEST_PREFIX=".tests-"

test_dir="${TEST_PREFIX}${GIT_AUTHOR_DATE% +*}"
git archive "$(git write-tree)" --prefix="$test_dir/" | tar xf -
cd "$test_dir"
if bash ./pipadoc.test 2>&1 | tee test.log ; then
    ret=$?

    # generate docs
    lua pipadoc.lua -m asciidoc pipadoc.lua >pipadoc.txt &&
        asciidoc -a toc pipadoc.txt &&
        grep -v '^// ' pipadoc.txt >"$WORKTREE_DIR/README" &&
        cd "$WORKTREE_DIR" &&
        if git diff --numstat README |
                { read a r f ; test $((a+r)) -gt 2; }; then
            mv "$test_dir/pipadoc.html" "$WORKTREE_DIR/"
            git add README pipadoc.html
        fi

    # cleanup old test dirs
    cd "$WORKTREE_DIR"
    find -name "${TEST_PREFIX}*" -type d | sort -n | head -n -$KEEP_TESTS | xargs -r rm -r

else
    ret=$?
    echo "testsuite failed, abort commit" 1>&2
fi

exit $ret
